linters-settings:
  staticcheck:
    go: "1.17"
    # https://staticcheck.io/docs/configuration/options/#checks
    checks:
      - "all" # default
      - "-ST1000" # default
      - "-ST1003" # default
      - "-ST1016" # default
      - "-ST1020" # default
      - "-ST1021" # default
      - "-ST1022" # default
      - "-ST1006" # SA1006: printf-style function with dynamic format string and no further arguments should use print-style function instead (staticcheck)
                  # https://github.com/nakamasato/golang-training/pull/36/checks?check_run_id=4721945149
