name: atlas

on:
  pull_request:
    paths:
      - 'pragmatic-cases/atlas/**.go'
      - 'go.*'
      - .github/workflows/atlas.yml
  push:
    branches:
      - main
jobs:
  mysql:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.3
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test_db
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: set up
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: run
        run: go run main.go
        env:
          MYSQL_HOST: localhost
          MYSQL_PASSWORD: password
          MYSQL_DB_NAME: test_db
        working-directory: pragmatic-cases/atlas
