name: ent

on:
  pull_request:
    paths:
      - 'pragmatic-cases/ent/**.go'
      - 'go.*'
      - .github/workflows/ent.yml
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: true

      - name: start postgres
        working-directory: pragmatic-cases/ent
        run: |
          docker-compose up -d
          while ! docker-compose ps | grep healthy; do echo 'postgres not ready. sleeping 3 sec'; sleep 3; done
          echo 'postgres is ready!'
          docker-compose exec -T postgres psql -U postgres postgres -c 'create database ent_getting_started;'
          docker-compose exec -T postgres psql -U postgres postgres -c 'create database ent_simple_example;'

      - name: run getting_started
        run: go run start/start.go
        working-directory: pragmatic-cases/ent/getting-started

      - name: check postgres records for getting_started
        working-directory: pragmatic-cases/ent
        run: |
          # https://github.com/docker/compose/issues/7306
          docker-compose exec -T postgres psql -U postgres postgres -d ent_getting_started -c 'select * from users'
          docker-compose exec -T postgres psql -U postgres postgres -d ent_getting_started -c 'select * from users' | grep '4 rows'
          docker-compose exec -T postgres psql -U postgres postgres -d ent_getting_started -c 'select * from cars'
          docker-compose exec -T postgres psql -U postgres postgres -d ent_getting_started -c 'select * from cars' | grep '5 rows'
          docker-compose exec -T postgres psql -U postgres postgres -d ent_getting_started -c 'select * from groups'
          docker-compose exec -T postgres psql -U postgres postgres -d ent_getting_started -c 'select * from groups' | grep '2 rows'
          docker-compose exec -T postgres psql -U postgres postgres -d ent_getting_started -c 'select * from group_users'
          docker-compose exec -T postgres psql -U postgres postgres -d ent_getting_started -c 'select * from group_users' | grep '3 rows'

      - name: run simple_example
        run: go run start/start.go
        working-directory: pragmatic-cases/ent/simple-example
