name: reviewdog
on:
  pull_request:
    paths:
      - '**.go'
jobs:
  golangci-lint:
    strategy:
      matrix:
        go: [ '1.17', '1.18' ]
    name: ${{ matrix.go }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          go_version: ${{ matrix.go }}
