name: skaffold

on:
  pull_request:
    paths:
      - 'pragmatic-cases/skaffold/**.go'
      - 'go.*'
      - .github/workflows/skaffold.yml
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup-go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: start kind cluster
        run: |
          echo "- kind version: $(kind version)" >> $GITHUB_STEP_SUMMARY
          kind create cluster

      - name: install skaffold
        if: steps.cache-skaffold.outputs.cache-hit != 'true'
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/

      - name: skaffold version
        run: |
          echo "- skaffold version: $(skaffold version)" >> $GITHUB_STEP_SUMMARY

      - name: run
        working-directory: pragmatic-cases/skaffold
        run: go run main.go
