name: test

on:
  pull_request:
    paths:
      - '**.go'
      - 'go.*'
      - .github/workflows/test.yml
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: set up
        uses: actions/setup-go@v3
        with:
          go-version-file: ./go.mod
          cache: true
      - uses: actions/checkout@v3
      - run: go test -coverprofile="coverage.txt" -covermode=atomic ./...
      - name: codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
